### ISSUE TITLE
The present-but-broken AbortController was fixed in Safari Technology Preview Release 74

### ISSUE THREAD

**Issue by macku** [mo/abortcontroller-polyfill#26]
The upcoming new version of Safari will ship the native Abordable Fetch controller. The latest preview release 74 released recently has fixed the missing API:
https://developer.apple.com/safari/technology-preview/release-notes/

The reported issue #23 and #24 pull requests weter supposed to fix the broken API, but in the recent version of Safari Preview, the polyfill brakes the browser runtime.

![image](https://user-images.githubusercontent.com/227305/51712418-d00f1f00-2082-11e9-94de-2d56b84d75a6.png)

**Comment by mo** [comment]
Ah right, if AbortController is fully working in the stable version; the polyfill needs to detect the working AbortController implementation and not install itself over it (while still installing itself on top of the broken AbortController versions in earlier Safari versions). PR welcome if you're up for it and otherwise I will take a look at this later at some point.

**Comment by macku** [comment]
I have created a fix that is checking the version of the Safari browser on desktop and also checks if we use iOS mobile device.

**Comment by getify** [comment]
Could we justify avoiding this extra complexity by just assuming that since Safari has now fixed their regression of a broken implementation, that eventually (soon) all users will be on a corrected Safari and thus we don't need to patch Safari at all?

**Comment by macku** [comment]
I guess we could if we are fine with shipping broken polyfill for the Safari 11. I was trying to use a more smart way of detecting the broken signal but it's an async operation and I don't think we can use it:

```js
const isAbortBrokenPromise = new Promise((resolve, reject) => {
  const controller = new AbortController();

  controller.abort();

  fetch('/', {
    signal: controller.signal,
  }).then(resolve, reject);
});

isAbortBrokenPromise.then(
  () => console.log('broken'),
  () => console.log('not broken')
);
```

**Comment by getify** [comment]
If I understand you correctly, I think what I'm suggesting is different. It's going back to how this polyfill worked before the reported breakage in 12.0.2. In other words, this polyfill would patch Safari 11 (since it has no `AbortController` at all, right?). And in 12.0.1-12.0.3, where the broken `AbortController` is present, this lib would not do anything... meaning breakage would exist in that window. But starting with 12.0.4 (or whatever), the real `AbortController` starts working. So it's really only breakage in that window of 12.0.1-12.0.3 or whatever. And I was asking if that breakage could be tolerable, given that most users will fairly quickly be upgraded to a Safari that has a working `AbortController`?

**Comment by macku** [comment]
> (since it has no AbortController at all, right?)

Sorry, my bad. The Safari 11 indeed doesn't ship the native `AbortContoller`. I've typed the wrong version in my previous comment.
There is an AbortController in Safari 12 but it doesn't work with fetch. I'm not sure why it was shipped in the first place but the integration with fetch API is missing.
https://caniuse.com/#feat=abortcontroller

>  I was asking if that breakage could be tolerable

I will live answeting that question to the author of the polyfill. In my opinion this might be problematic for some time only.

**Comment by chen86860** [comment]
Same issues in iOS 12.2 beta :(

Hope guys can fix it.

**Comment by mo** [comment]
Fixed on master now and released to npm as v1.2.3

The fixed version should "just work" on all browsers / browser versions, including Safari 12.0.x, 12.2 etc and Chrome/Firefox for IOS. 

Please file another github ticket if you find any remaining issue for some browser / browser version.

**Comment by kgusarov** [comment]
Problem still here... Also, this solution looks kinda... broken to me:
```
  if (userAgent.match(/ Safari\//i) && (
    userAgent.match(/ Version\/12.0/i) ||
    userAgent.match(/ Version\/12.1/i)
  )) {
    return true;
  }
```
I mean, what will happen, when new Safari version will appear - new release? Maybe, it is better to think of other solution here...

![51136439_550111022160272_4688328713392095232_n](https://user-images.githubusercontent.com/1231997/52331254-57a04a80-2a00-11e9-8f42-11723e1aa178.jpg)

**Comment by mo** [comment]
@kgusarov this fix handles the broken AbortController in 12.1.x  and also in all 12.2.x releases (even future point releases and major releases). When a stable 12.3 is released it will have the working native AbortController.

So the fix should work for your 12.1 release too. Can you enter "navigator.userAgent" into the devtools console and paste the output here?

**Comment by kgusarov** [comment]
@mo 
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1 Safari/605.1.15` - should in theory fall under regex...

**Comment by mo** [comment]
@kgusarov do you have any "user agent switching" browser extension installed or some "privacy / anti tracking" browser extension that prevents JS from reading navigator.userAgent? I assume you have already double checked that you really have version 1.2.3 and that there isn't some cache issue that prevents the latest version of the polyfill from loading.

**Comment by kgusarov** [comment]
@mo this problem is on our client's laptop, he was nice enough to bring to our office(!) for us to check the problem. No extensions are used there, and even dev tools were initially disabled. We checked everything, and the fix still doesn't work.

**Comment by youennf** [comment]
Thanks for fixing the polyfill.
As of the check, one could also feature detect the presence of 'signal' in the Request prototype.
